default: &default
  adapter: postgresql
  username: gra1
  password:
  host: localhost
  encoding: utf8
  pool: 12
  wait_timeout: 10

development:
  <<: *default
  database: team-to-travel_development

test:
  <<: *default
  database: team-to-travel_test

production:
  <<: *default
  database: team-to-travel_production
